version: '3'

services:
  turing-machine:
    image: php:7.4-apache
    container_name: turing-machine
    ports:
      - 8443:80
    volumes:
      - ./:/var/www/html
      - ./php.ini:/etc/php/7.4/apache2/php.ini
    networks:
      - turing-network

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - turing-network

networks:
  turing-network:
    driver: bridge
